### ISSUE TITLE
Cannot clean up EmmyLua from Sumneko's libraries path on uninstall

### ISSUE THREAD

**Issue by Ketho** [Ketho/vscode-wow-api#20]
Uninstalling the extension does not appear to work, starting somewhere around the August 2021 vscode release.
It relied on vscode deleting the actual extension files instead of marking them in:
```
C:\Users\<user>\.vscode\extensions\.obsolete
```

Removing them from Sumneko's external libraries path does not seem possible when uninstalling, since we don't have access to the vscode api in the [uninstall hook](https://code.visualstudio.com/api/references/extension-manifest#extension-uninstall-hook).
* https://github.com/microsoft/vscode/issues/45474
* https://github.com/sumneko/lua-language-server/wiki/EmmyLua-Libraries

**Comment by ChrisKader** [comment]
It seems the options are pretty limited as there is no notification to the extension that's its being uninstalled while also providing access to an API that makes it possible to remediate extension settings.

**Comment by ChrisKader** [comment]
It may be good if Sumneko's Language Server exposed an API or command for adding/removing library paths (instead of requiring that extensions update its config to add them).

As it currently stands, there is no way to update the config of Sumneko's Language Server extension to remove added library paths (and there does not appear to be any plan to support such a feature that would allow for that to happen).

However, if Sumneko's extension exposed an API or command (both possible for a VS code extension to do) for adding/removing library paths then vscode-wow-api could invoke that API or command on activation and deactivation.

**Comment by Ketho** [comment]
Then I should probably make a ticket at least for Sumneko explaining my issue. But I'm not sure if this is something they would want to spend dev time on possible solutions like an API for plugin extensions like this one.

**Comment by ChrisKader** [comment]
At high level this appears to be a best practice as its done by other language server extensions for embedded languages. This type of API would also provide the benefit of being able to more efficiently load libraries. I dont think he should remove the ability to provide a path to libraries in his extension. I do believe that this API should be an option though, since its one that is implemented by other language servers and even the one built into VS Code.

**Comment by Ketho** [comment]
The extension files get cleaned up (since a year I guess)
