### ISSUE TITLE
Region:IsMouseOver

### ISSUE THREAD

**Issue by Torhal** [Ketho/vscode-wow-api#97]
I'm not sure what to edit on the [Wiki page](https://wowpedia.fandom.com/wiki/API_ScriptRegion_IsMouseOver) to correct the definition in the extension, but there are two problems:

- The type definition in the extension requires all parameters, but they're all optional.
- The Wiki says this is a ScriptRegion method, where the extension uses Region.

If this is actually something I could fix myself via the Wiki page for the next extension release, I'd like to know so I skip the ticket-filing process if/when this happens again.

**Comment by Ketho** [comment]
- The wiki page here is right, the extension is very much out of date with regards to widget API.
- The wiki now tries to use the blizzard generated widget docs (since 10.0.0) but I have been lazy with updating the extension to match this.

In general I try to update the wiki docs first before updating the extension. Currently I'm having trouble prioritizing my time between my education and other work.

> If this is actually something I could fix myself via the Wiki page for the next extension release, I'd like to know so I skip the ticket-filing process if/when this happens again.

Do you mean updating the wiki pages? The extension doesn't really pull the emmylua docs from the widget api pages so it still needs to be updated manually in the extension. Ideally it would be updated from `Blizzard_APIDocumentationGenerated`.

If you want to have contributor access to the repository I'd be happy to oblige.

This is the current state of the widget docs with regards to blizzard api documentation if it helps.

![image](https://user-images.githubusercontent.com/1073877/236056460-cfb936d6-ecfb-4595-83a1-97b796d81be5.png)

**Comment by Ketho** [comment]
The vscode extension and wiki docs should have proper support for Widget API for a while now 🙂
